# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
# use this to find packages: https://anaconda.org/
name: qbic-pipelines-vcreport-1.0.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-base=3.5.1
  - r::r-hexbin=1.27.2
  - conda-forge::r-svglite=1.2.3
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-gplots=3.0.3
  - r::r-plyr=1.8.4
  - conda-forge::r-ggplot2=3.3.0
  - conda-forge::r-rcolorbrewer=1.1_2
  - conda-forge::cairo=1.16.0
  - conda-forge::r-optparse=1.6.4
  - conda-forge::r-extrafont=0.17
  - conda-forge::r-knitr=1.28
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-dt=0.13
  - r::r-yaml=2.2.0 # chose R channel because conda-forge has only 0.1.7
  - conda-forge::r-rmarkdown=2.1
  - r::r-dplyr=0.7.6
  - conda-forge::r-kableextra=1.1.0
  - conda-forge::r-formattable=0.2.0.1
  - conda-forge::r-rlist=0.4.6.1
